### ISSUE TITLE
auth.js fails when to set to ng-strict-di="true"

### ISSUE THREAD

**Issue by rhymiz** [Foxandxss/sails-angular-jwt-example#8]
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:strictdi] function($httpProvider) is not using explicit annotation and cannot be invoked in strict mode

**Comment by Foxandxss** [comment]
Project is completely non minification safe. It is just an old demo.

**Comment by rhymiz** [comment]
Got it. Any suggestions for getting that part to work? I'm super new to Angular.
I checked their documentation to get it working, but, if I follow their instructions, every request that I make as logged in user, returns a 401 Unauthorized.

**Comment by Foxandxss** [comment]
The strict-di mode and the 401 are not related. It is better if you go to stackoverflow with your entire problem, described, with examples. That is most likely to yield you an answer.

**Comment by rhymiz** [comment]
Fixed it. Thanks for your time.

AuthInterceptor becomes that of the below function and the factory looks like this:

`.factory('AuthInterceptor', AuthInterceptor)`

----

 function AuthInterceptor($q, $injector) {

    var LocalService = $injector.get('LocalService');
    return {
        request: function (config) {
            var token;
            if (LocalService.get('auth_token')) {
                token = angular.fromJson(LocalService.get('auth_token')).token;
            }
            if (token) {
                config.headers.Authorization = 'Bearer ' + token;
            }
            return config;
        },
        responseError: function (response) {
            if (response.status === 401 || response.status === 403) {
                LocalService.unset('auth_token');
                $injector.get('$state').go('anon.login');
            }
            return $q.reject(response);
        }
    }
}

**Comment by mojtabaramezani** [comment]
tkle
